### ISSUE TITLE
Configurar Travis

### ISSUE THREAD

**Issue by tomasBustamante** [Gaston11/TP-DragonAlgo-Ball-#1]
Falta el arvhico yml necesario para Travis:
```
language: java
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
```
Acá está la documentación del formato: https://docs.travis-ci.com/user/languages/java/

Además faltan los archivos `ivy.xml` y `build.xml` y los directorios `src` y `test` en la raíz del repositorio.
